---@meta

--- This file is auto-generated by wayglance. Do not edit manually.

--- The `wayglance` module, which provides helper functions for dynamic bindings and event
--- handling.
wayglance = {}

--- The `hyprland` module, which provides functions for querying Hyprland state and dispatching
--- commands, as well as forwarding events from the Hyprland IPC listener.
--- 
--- ### Signals
--- The following signals are emitted on the `wayglance` signal bus:
--- - `hyprland::workspace_changed` : Emitted when the user switches to a different workspace.
--- Data: `HyprlandWorkspace`
--- - `hyprland::workspace_added` : Emitted when a new workspace is created.
--- Data: `HyprlandWorkspace`
--- - `hyprland::workspace_deleted` : Emitted when a workspace is destroyed.
--- Data: `HyprlandWorkspace`
--- - `hyprland::workspace_moved` : Emitted when a workspace is moved to another monitor.
--- Data: `HyprlandWorkspace`
--- - `hyprland::workspace_renamed` : Emitted when a workspace is given a new name.
--- Data: `HyprlandWorkspace`
--- - `hyprland::active_window` : Emitted when the focused window changes.
--- Data: `HyprlandWindow`
--- - `hyprland::fullscreen_changed` : Emitted when the active window's fullscreen state toggles.
--- Data: `boolean`
--- - `hyprland::active_monitor_changed` : Emitted when focus moves to a different monitor.
--- Data: `HyprlandActiveMonitor`
wayglance.hyprland = {}

--- The z-level layer where the window will be placed.
---@alias Layer "background" | "bottom" | "top" | "overlay"

--- Orientation for container widgets.
---@alias Orientation "horizontal" | "vertical"

--- Alignment for widgets within their parent container.
---@alias Alignment "start" | "center" | "end" | "fill" | "baseline"

--- Information about the currently active window in Hyprland, including its title, class, PID,
--- monitor, workspace, position, size, and other states.
---@class HyprlandActiveWindowInfo
---@field address string The unique hex address of the window.
---@field title string The title of the active window.
---@field initial_title string The initial title of the window when it was first created.
---@field class string The class of the active window.
---@field initial_class string The initial class of the window when it was first created.
---@field pid number The process ID of the active window.
---@field monitor ? number The ID of the monitor the active window is on, if available.
---@field workspace HyprlandWorkspace Basic information about the workspace the active window is on.
---@field width number The width of the window in pixels.
---@field height number The height of the window in pixels.
---@field x number The x-coordinate of the window's top-left corner.
---@field y number The y-coordinate of the window's top-left corner.
---@field floating boolean Whether the window is currently floating.
---@field fullscreen boolean Whether the window is currently in fullscreen mode.
local HyprlandActiveWindowInfo = {}

--- Basic information about a window, including its title and class.
---@class HyprlandWindow
---@field title string The title of the window.
---@field class string The class of the window.
local HyprlandWindow = {}

--- A container widget that can hold multiple child widgets, arranged either horizontally or
--- vertically.
---@class Container : Widget
---@field orientation Orientation The orientation of the container.
---@field spacing ? number The spacing between children in the container, in pixels. (Default: 0)
---@field children ? Widget[] | State The child widgets contained within this container.
---@field id ? string | State Optional widget ID, used for CSS styling and querying.
---@field class_list ? string[] | State Optional list of CSS classes applied to the widget.
---@field halign ? Alignment | State Optional horizontal alignment for the widget.
---@field valign ? Alignment | State Optional vertical alignment for the widget.
---@field hexpand ? boolean | State Whether the widget should expand to fill available horizontal space. (Default: false)
---@field vexpand ? boolean | State Whether the widget should expand to fill available vertical space. (Default: false)
---@field visible ? boolean | State Whether the widget is visible. (Default: true)
---@field tooltip ? string | State Optional tooltip markup text for the widget.
local Container = {}

--- A clickable button widget.
---@class Button : Widget
---@field on_click function Function to execute when the button is clicked.
---@field child Widget The child widget to display inside the button.
---@field id ? string | State Optional widget ID, used for CSS styling and querying.
---@field class_list ? string[] | State Optional list of CSS classes applied to the widget.
---@field halign ? Alignment | State Optional horizontal alignment for the widget.
---@field valign ? Alignment | State Optional vertical alignment for the widget.
---@field hexpand ? boolean | State Whether the widget should expand to fill available horizontal space. (Default: false)
---@field vexpand ? boolean | State Whether the widget should expand to fill available vertical space. (Default: false)
---@field visible ? boolean | State Whether the widget is visible. (Default: true)
---@field tooltip ? string | State Optional tooltip markup text for the widget.
local Button = {}

--- A simple widget that displays a text label.
---@class Label : Widget
---@field text string | State The text content of the label. Can be a static string or a dynamic expression that evaluates to a string.
---@field id ? string | State Optional widget ID, used for CSS styling and querying.
---@field class_list ? string[] | State Optional list of CSS classes applied to the widget.
---@field halign ? Alignment | State Optional horizontal alignment for the widget.
---@field valign ? Alignment | State Optional vertical alignment for the widget.
---@field hexpand ? boolean | State Whether the widget should expand to fill available horizontal space. (Default: false)
---@field vexpand ? boolean | State Whether the widget should expand to fill available vertical space. (Default: false)
---@field visible ? boolean | State Whether the widget is visible. (Default: true)
---@field tooltip ? string | State Optional tooltip markup text for the widget.
local Label = {}

--- A handle to a reactive state entry. Contains the state ID and an optional transform function.
--- Can be used on properties that support it (e.g. `label.text`) to provide dynamic values that
--- automatically update when the state changes.
--- Provides methods to either read, write or bind with/out a transform function.
--- 
--- # INTERNAL USE ONLY
--- Not intended for direct use. Should only be constructed via the `wayglance.state()` Lua
--- function, which ensures the state is properly registered and rooted in the Lua registry.
---@class State
---@field id number The ID of this state in the registry.
---@field transform ? function An optional Lua transform function applied when this state is used as a binding. Stored as a registry key so it survives across Lua calls.
local State = {}

--- A handle that can be used to cancel a scheduled task or a signal subscription.
---@class CancelHandle
local CancelHandle = {}

--- Common properties shared by all widgets (layout, CSS classes, IDs, etc).
---@class Widget
---@field id ? string | State Optional widget ID, used for CSS styling and querying.
---@field class_list ? string[] | State Optional list of CSS classes applied to the widget.
---@field halign ? Alignment | State Optional horizontal alignment for the widget.
---@field valign ? Alignment | State Optional vertical alignment for the widget.
---@field hexpand ? boolean | State Whether the widget should expand to fill available horizontal space. (Default: false)
---@field vexpand ? boolean | State Whether the widget should expand to fill available vertical space. (Default: false)
---@field visible ? boolean | State Whether the widget is visible. (Default: true)
---@field tooltip ? string | State Optional tooltip markup text for the widget.
local Widget = {}

--- The top-level configuration for the wayglance application shell.
--- 
--- A `Shell` acts as a container for global configuration (like the application title and styles)
--- and a list of [`Window`] definitions that define the UI structure.
---@class Shell
---@field title string The global title of the shell, which determines the GTK `application_id`.
---@field style ? string Path to an optional global CSS stylesheet.
---@field windows Window[] All the window definitions registered in this shell.
local Shell = {}

--- Detailed information about a physical monitor where a shell window is being displayed.
---@class Monitor
---@field name string The name of the monitor (e.g., "eDP-1").
---@field id number The unique identifier for the monitor (currently defaults to -1).
---@field width number The width of the monitor in pixels.
---@field height number The height of the monitor in pixels.
---@field refresh_rate number The refresh rate of the monitor in Hz.
---@field scale number The UI scale factor (e.g., 1.0, 2.0).
local Monitor = {}

--- Anchor points for the window to stick to specific edges of the monitor.
---@class Anchors
---@field top ? boolean Whether to anchor the window to the top edge of the monitor. (Default: false)
---@field right ? boolean Whether to anchor the window to the right edge of the monitor. (Default: false)
---@field bottom ? boolean Whether to anchor the window to the bottom edge of the monitor. (Default: false)
---@field left ? boolean Whether to anchor the window to the left edge of the monitor. (Default: false)
local Anchors = {}

--- Margin in pixels from each edge of the monitor.
---@class Margins
---@field top ? number Margin from the top edge of the monitor, in pixels. (Default: 0)
---@field right ? number Margin from the right edge of the monitor, in pixels. (Default: 0)
---@field bottom ? number Margin from the bottom edge of the monitor, in pixels. (Default: 0)
---@field left ? number Margin from the left edge of the monitor, in pixels. (Default: 0)
local Margins = {}

--- Basic information about a workspace, including its ID and name.
---@class HyprlandWorkspace
---@field id number The unique identifier for the workspace.
---@field name string The name of the workspace.
local HyprlandWorkspace = {}

--- Detailed information about a workspace in Hyprland, including its ID, name,
--- associated monitor, number of windows, last focused window title, and whether it is fullscreen.
---@class HyprlandWorkspaceInfo : HyprlandWorkspace
---@field monitor string The name of the monitor this workspace is on.
---@field windows number The number of windows currently on this workspace.
---@field last_window_title string The title of the last focused window on this workspace.
---@field fullscreen boolean Whether this workspace is currently in fullscreen mode.
---@field monitor_id ? number The unique identifier of the monitor this workspace is on.
---@field id number The unique identifier for the workspace.
---@field name string The name of the workspace.
local HyprlandWorkspaceInfo = {}

--- Information about a monitor in Hyprland, including its ID, name, resolution,
--- position, and currently active workspace.
---@class HyprlandMonitorInfo
---@field id number The unique identifier for the monitor.
---@field name string The name of the monitor, as configured in Hyprland.
---@field focused boolean Whether this monitor is currently focused (i.e., has the active workspace).
---@field width number The width of the monitor in pixels.
---@field height number The height of the monitor in pixels.
---@field x number The x-coordinate of the monitor's top-left corner.
---@field y number The y-coordinate of the monitor's top-left corner.
---@field refresh_rate number The refresh rate of the monitor in Hz.
---@field scale number The UI scale factor for the monitor.
---@field active_workspace HyprlandWorkspace Basic information about the currently active workspace on this monitor.
local HyprlandMonitorInfo = {}

--- Basic information about an active monitor, including its name and the name of the active
--- workspace.
---@class HyprlandActiveMonitor
---@field monitor string The name of the monitor.
---@field workspace ? string The name of the workspace on the monitor, if available.
local HyprlandActiveMonitor = {}

--- A window that can be instantiated on one or more monitors.
---@class Window
---@field name ? string The unique name of this window, used for identification and debugging. (Default: Gets the name from `window` method)
---@field monitors ? string[] A list of monitor connector names to display this window on. If empty, all monitors.
---@field layer Layer The layer to display this window on.
---@field exclusive_zone ? boolean Whether this window should reserve space on the monitor (like a panel) or be free-floating. (Default: false)
---@field anchors ? Anchors The edges of the monitor to anchor this window to.
---@field margins ? Margins The margins to apply on each edge when anchored.
---@field layout any The layout of the window. Can be a table (static widget) or a function (monitor) -> widget.
local Window = {}

--- Returns information about the currently active window in Hyprland, including its title, class,
--- PID, monitor, workspace, position, and size. If there is no active window, a nil value is
--- returned.
---@return HyprlandActiveWindowInfo | nil active_window A table containing information about the currently active window, or nil if there is no active window.
function wayglance.hyprland.getActiveWindow() end

--- Toggles the fullscreen state of the currently active window in Hyprland.
function wayglance.hyprland.toggleFullscreen() end

--- Toggles the floating state of the currently active window in Hyprland.
function wayglance.hyprland.toggleFloating() end

--- Closes the currently active window in Hyprland.
function wayglance.hyprland.killActiveWindow() end

--- Creates a new shell configuration.
---@param config table The global shell configuration.
---@return Shell shell The shell object.
function wayglance.shell(config) end

--- Schedules the provided callback to be called repeatedly at the specified interval (in ms).
---@param callback function The callback to call after interval ms have passed.
---@param interval number The interval in milliseconds to wait before calling the callback.
---@return CancelHandle handle A handle that can be used to cancel the scheduled callback with :cancel().
function wayglance.setInterval(callback, interval) end

--- Creates a new reactive state with the given initial value.
--- Can be used on properties that support it (e.g. `label.text`) to provide dynamic values that
--- automatically update when the state changes.
--- 
--- # Example:
--- ```lua
--- local count = wayglance.state(0)
--- 
--- -- ... inside layout:
--- Label({ text = count:bind(function(count)
--- return "Count: " .. count
--- end) }) -- bind state to label text with transform function
--- 
--- -- ... somewhere else in the code:
--- wayglance.setInterval(function()
--- local current = count:get() -- read current state value
--- count:set(current + 1) -- update state value, triggers UI update
--- end, 1000) -- repeat every 1000 ms
--- ```
---@param initial any The initial value of the state.
---@return State state A reactive state handle.
function wayglance.state(initial) end

--- Creates a new state binding with a transform function that maps the state value to a new value.
---@param transform function A function that transforms the state value and returns the transformed result.
---@return table
function State:bind(transform) end

--- Updates the value of a reactive state and notifies all subscribers.
---@param value any The new value to set for the state.
function State:set(value) end

--- Retrieves the current value of a reactive state.
---@return any
function State:get() end

--- Cancels the scheduled task or signal subscription.
function CancelHandle:cancel() end

--- Listen for one or more signals and call the provided callback when they are emitted.
---@param signals string | string[] The signal or signals to listen for.
---@param callback function The callback to call when the signal(s) are emitted.
---@return CancelHandle handle A handle that can be used to cancel the signal subscription with :cancel().
function wayglance.onSignal(signals, callback) end

--- Emit a signal with the given name and optional data payload.
---@param signal string The name of the signal to emit.
---@param data ? any Optional data to include with the signal. Can be any Lua value.
function wayglance.emitSignal(signal, data) end

--- Adds a new window definition to the shell configuration.
---@param name string The unique name of the window.
---@param config Window The configuration for this window.
function Shell:window(name, config) end

--- Switches the focus to the workspace with the given numerical ID.
---@param workspace_id number The numerical ID of the workspace to switch to.
function wayglance.hyprland.switchWorkspace(workspace_id) end

--- Moves the currently active window to the workspace with the given numerical ID without
--- switching focus to that workspace.
---@param workspace_id number The numerical ID of the workspace to move the window to.
function wayglance.hyprland.moveActiveToWorkspaceSilent(workspace_id) end

--- Switches the focus to a workspace relative to the current one (e.g., +1 or -1).
---@param offset number The relative offset from the current workspace (e.g., 1 for next, -1 for previous).
function wayglance.hyprland.switchWorkspaceRelative(offset) end

--- Returns a list of all current workspaces in Hyprland, including their IDs, names,
--- associated monitors, and status information.
---@return HyprlandWorkspaceInfo[] workspaces A list of information about all current workspaces.
function wayglance.hyprland.getWorkspaces() end

--- Toggles a special workspace (scratchpad) with the given name. If no name is provided,
--- the default special workspace is used.
---@param workspace_name ? string Optional name of the special workspace to toggle. If nil, the default special workspace is used.
function wayglance.hyprland.toggleSpecialWorkspace(workspace_name) end

--- Switches the focus back to the previously active workspace.
function wayglance.hyprland.switchToPreviousWorkspace() end

--- Switches the focus to the workspace with the given name.
---@param workspace_name string The name of the workspace to switch to.
function wayglance.hyprland.switchWorkspaceNamed(workspace_name) end

--- Moves the currently active window to the workspace with the given numerical ID.
---@param workspace_id number The numerical ID of the workspace to move the window to.
function wayglance.hyprland.moveActiveToWorkspace(workspace_id) end

--- Returns a list of Hyprland monitors, including their IDs, names, and focus status.
---@return HyprlandMonitorInfo[] monitors A list of information about all connected monitors.
function wayglance.hyprland.getMonitors() end

--- A container widget that can hold multiple child widgets, arranged either horizontally or
--- vertically.
---@param config Container The configuration table for the Container widget.
---@return Widget widget The constructed widget.
function Container(config) end

--- A clickable button widget.
---@param config Button The configuration table for the Button widget.
---@return Widget widget The constructed widget.
function Button(config) end

--- A simple widget that displays a text label.
---@param config Label The configuration table for the Label widget.
---@return Widget widget The constructed widget.
function Label(config) end
